# 列表List
- 一个列表可以储存任意大小的数据集合，你可以理解为他是一个容器

In [2]:
a = []#列表
a

[]

In [6]:
a = [1,2,3,'a',[1,2],'b']
a

[1, 2, 3, 'a', [1, 2], 'b']

## 先来一个例子爽一爽
![](../Photo/115.png)

## 创建一个列表
- a = [1,2,3,4,5]

In [7]:
a = [[1,2],[3,4]]
a

[[1, 2], [3, 4]]

In [9]:
import numpy as np

In [10]:

a = [[1,2],[3,4]]
np.array(a)

array([[1, 2],
       [3, 4]])

## 列表的一般操作
![](../Photo/116.png)

In [1]:
a=[1,2,3]
min(a)

1

In [2]:
a=[1,2,3]
max(a)

3

In [3]:
a=[1,2,3]
sum(a)

6

In [4]:
a=[1,2,3]
for i in a:
    print(i)

1
2
3


In [11]:
a='stella'
b='st'
b in a

True

In [14]:
a=[1,2,3,'stella',1.2]
b='st'
b in a

False

In [15]:
a=[1,2,3,'stella',1.2]
b='st'
b not in a

True

In [16]:
#列表不能相减，不能相除。只能相加，相乘。
a=[1]
b=[2]
a+b

[1, 2]

In [17]:
a=[1]
b=[2]
b+a

[2, 1]

In [24]:
a=[1]
b=5
a*b

[1, 1, 1, 1, 1]

In [21]:
a=[1,2,3,4,5]
a[2]


3

In [27]:
a=[1,2,4,5]
a[3:0:-1]


[5, 4, 2]

In [28]:
a = [1,2,4,5]
a[::2]

[1, 4]

In [29]:
a = [1,2,4,5]
a[0:3]

[1, 2, 4]

In [30]:
a = [1,2,4,5,[100,200,300]]
a[0:4][2]

4

In [31]:
a = [1,2,4,5,[100,200,300]]
a[4][2]

300

In [ ]:
for i in range(0,4):
    if i == 0 or i == 3:
        print('*'*5)
    else:
        print('*'+' '*3+'*')

In [37]:
for i in range(0,3):
    if i == 0:
        print([123])
    elif i ==1:
        print([456])
    elif i ==2:
        print([789])
        for i in range(0,3):
            if b=i[0:2][0][0:2]:
                print(b)
            elif c=a[0:2][1][0:2]:
                print(c)
                

IndentationError: unexpected indent (<ipython-input-37-083673117670>, line 9)

In [40]:
for i in range(2):
    for j in range(2):
        print(i,i+2,j,j+2)

0 2 0 2
0 2 1 3
1 3 0 2
1 3 1 3


In [41]:
a = [[1,2,3],[4,5,6],[7,8,9]]
aa=np.array(a)
aa

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
aa[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [43]:
for i in range(2):
    for j in range(2):
        print(a[i][j:j+2])
        print(a[i+1][j:j+2])
        print('----------')

[1, 2]
[4, 5]
----------
[2, 3]
[5, 6]
----------
[4, 5]
[7, 8]
----------
[5, 6]
[8, 9]
----------


In [44]:
a = [1,2,3,[1,2,3]]
len(a)

4

In [53]:
a = [1,2,3,[1,2,3]]
a[4]

IndexError: list index out of range

# 列表索引操作
- Mylist[index]
- 正序索引，逆序索引
- 列表一定注意越界
- ![](../Photo/117.png)

## 列表切片操作
- Mylist[start:end]
- 正序切片，逆序切片

## 列表 +、*、in 、not in

## 使用for循环遍历元素
- for 循环可以遍历一切可迭代元素

## EP：
- 使用while 循环遍历列表

In [5]:
bb=[1,2,3,4,5]
for i in bb:
    print(i)

1
2
3
4
5


In [4]:
i=0
while i<len(bb):
    print(bb[i])
    i+=1

1
2
3
4
5


## 列表的比较
- \>,<,>=,<=,==,!=

## 列表生成式
[x for x in range(10)]

In [5]:
U = [x for x in range(10)]
U

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
U = [x+100 for x in range(10)]
U

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109]

In [7]:
U = [x for x in range(10) if x%2==0]
U

[0, 2, 4, 6, 8]

In [8]:
import random

In [9]:
K=[random.randint(0,10)for i in range(10)]
K

[2, 5, 7, 4, 7, 2, 3, 8, 1, 10]

In [10]:
b=[]
a=[1,2,3,[1,2,3]]
for i in a:
    if type(i) is list:
        b.extend(i)
    else:
        b.append(i)
b

[1, 2, 3, 1, 2, 3]

In [11]:
b=[1,2,3]
b.remove(100)

ValueError: list.remove(x): x not in list

## 列表的方法
![](../Photo/118.png)

In [29]:
a=[1,2,10,4,6]


In [30]:
for i in range(len(a)):
    for j in range(len(a)-i-1):
#        print(a[j],a[j+1])
        if a[j]>a[j+1]:
            a[j],a[j+1]=a[j+1],a[j]
        print(a)
    break

[1, 2, 10, 4, 6]
[1, 2, 10, 4, 6]
[1, 2, 4, 10, 6]
[1, 2, 4, 6, 10]


In [15]:
b=[1,2,3]
b.reverse()
b

[3, 2, 1]

In [22]:
a=[1,2,10,4,6]
a.sort(reverse=True)
a

[10, 6, 4, 2, 1]

In [11]:
a=10
b=[100]
b.append(a)

In [12]:
b

[100, 10]

In [1]:
a=[1,2,3,4]
b=[100,200,300,400]
for i in b:
    a.append(i)
a


[1, 2, 3, 4, 100, 200, 300, 400]

In [3]:
a=[1,2,3,4]
b=[100,200,300,400]
a.append(b[1:3])
a

[1, 2, 3, 4, [200, 300]]

In [8]:
a=[1,2,2,[2,2],3]
for i in a:
    print(a.count(2))
a


2
2
2
2
2


[1, 2, 2, [2, 2], 3]

In [9]:
a=[1,2,3,4,1]
a.insert(2,100)

In [10]:
a

[1, 2, 100, 3, 4, 1]

In [13]:
b=[1,2,3,4,6]
for i in b:
    if i %2==0 and i !=100:
        index_=b.index(i)
        b.insert(index_,100)
        break
b

[1, 100, 2, 3, 4, 6]

In [14]:
a=[1,1,1,2,3]
a.remove(1)

In [15]:
a

[1, 1, 2, 3]

## 将字符串分割成列表
- split  按照自定义的内容拆分

## EP:
![](../Photo/119.png)
![](../Photo/120.png)

## 列表的复制
- copy 浅复制
- deepcopy import copy  深复制
- http://www.pythontutor.com/visualize.html#mode=edit

## 列表排序
- sort
- sorted
- 列表的多级排序
    - 匿名函数

In [32]:
a=[1,2,3,0]
a.sort()
a

[0, 1, 2, 3]

In [35]:
(lambda x:print(x))(100)

100


In [36]:
a=[['ZWJ',60],['ZOF',20],['WJJ',100],['HX',1]]
a.sort(key=lambda x:x[1])
a

[['HX', 1], ['ZOF', 20], ['ZWJ', 60], ['WJJ', 100]]

## EP：
- 手动排序该列表[5,3,8,0,17]，以升序或者降序

- 1
![](../Photo/121.png)

In [2]:

a=eval(input('请输入成绩列表：'))
b=max(a)
for i in a:
    if i>=b-10:
        print(i,'级别A')
    elif i>=b-20:
        print(i,'级别B')
    elif i>=b-30:
        print(i,'级别C')            
    elif i>=b-40:
        print(i,'级别D')
    else:
        print(i,'成绩为F！')

请输入成绩列表：40,55,70,58
40 级别C
55 级别B
70 级别A
58 级别B


- 2
![](../Photo/122.png)

In [1]:
#逆序读取的数字
a = eval(input('请输入一个整数列表：'))
print(a[::-1])

请输入一个整数列表：1,2,3
(3, 2, 1)


- 3
![](../Photo/123.png)

In [3]:
#统计数字个数
a=[1,2,3,2]
for i in a:
    if i>100:
        pass
    else:
        b=a.count(i)       
        print(i,b)    

1 1
2 2
3 1
2 2


- 4
![](../Photo/124.png)

In [4]:
#分析成绩
a = [60,65,67,78,87,89,91,99]
b = sum(a)/len(a)
num1 = 0
num2 = 0
for i in a:
    if i > b:
        num1 += 1
    if i < b:
        num2 += 1   
print('大于平均数的值为：',num1)
print('小于平均数的值为：',num2)

大于平均数的值为： 4
小于平均数的值为： 4


- 5
![](../Photo/125.png)

In [6]:
#统计单个数字
import random
U = [random.randint(0,9) for i in range(1000) ]
U

[5,
 9,
 9,
 5,
 0,
 5,
 4,
 1,
 6,
 4,
 5,
 7,
 5,
 3,
 0,
 5,
 6,
 3,
 5,
 2,
 0,
 4,
 9,
 4,
 1,
 0,
 2,
 2,
 1,
 8,
 8,
 7,
 0,
 9,
 7,
 5,
 0,
 5,
 4,
 2,
 3,
 8,
 6,
 1,
 3,
 9,
 0,
 6,
 4,
 8,
 2,
 5,
 0,
 4,
 1,
 8,
 7,
 2,
 6,
 1,
 2,
 1,
 7,
 6,
 4,
 2,
 6,
 4,
 8,
 7,
 9,
 7,
 8,
 6,
 0,
 7,
 6,
 8,
 2,
 1,
 3,
 3,
 6,
 9,
 4,
 7,
 2,
 4,
 0,
 9,
 6,
 4,
 3,
 6,
 4,
 7,
 0,
 6,
 3,
 3,
 8,
 9,
 5,
 7,
 7,
 2,
 8,
 6,
 2,
 5,
 7,
 6,
 7,
 6,
 8,
 8,
 9,
 9,
 7,
 6,
 0,
 4,
 2,
 3,
 4,
 1,
 8,
 9,
 3,
 4,
 1,
 9,
 4,
 9,
 6,
 5,
 5,
 5,
 8,
 5,
 3,
 3,
 7,
 8,
 7,
 1,
 9,
 8,
 6,
 3,
 7,
 6,
 3,
 2,
 4,
 2,
 1,
 0,
 5,
 2,
 6,
 8,
 5,
 6,
 3,
 5,
 2,
 9,
 8,
 1,
 0,
 9,
 4,
 9,
 7,
 1,
 2,
 6,
 6,
 3,
 5,
 7,
 2,
 0,
 5,
 0,
 7,
 5,
 6,
 9,
 8,
 0,
 9,
 2,
 7,
 1,
 7,
 8,
 2,
 0,
 9,
 5,
 6,
 0,
 5,
 1,
 6,
 2,
 6,
 8,
 5,
 5,
 2,
 6,
 3,
 9,
 9,
 9,
 5,
 0,
 2,
 2,
 9,
 8,
 1,
 2,
 3,
 5,
 1,
 8,
 3,
 3,
 1,
 6,
 1,
 6,
 9,
 9,
 3,
 3,
 5,
 4,
 8,
 0,
 3,
 8,
 4,
 2,
 9,
 6,


- 6
![](../Photo/126.png)

In [16]:
#找出最小元素的下标
def gg():
    print('输入一个数字列表:')
    a = input(">>")
    b = min(a)
    c = a.index(b)
    print(c)

In [17]:
h=gg()

输入一个数字列表:
>>2,3,4
1


- 7
![](../Photo/127.png)
![](../Photo/128.png)

In [18]:
#随机数字选择器
def bb():
    a = [1,2,3]  
    random.shuffle(a)
    print(a)

In [21]:
a=bb()

[2, 3, 1]


- 8
![](../Photo/129.png)

- 9
![](../Photo/130.png)

- 10
![](../Photo/131.png)

- 11
![](../Photo/132.png)

- 12
![](../Photo/133.png)